# Generated by Django 3.2.4 on 2021-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweep',
            name='tweep',
            field=models.TextField(default='default'),
        ),
    ]
